### PR TITLE
feat(Textfield): Add textarea option

### PR DESCRIPTION
**Pull request by martahj**
Adds an option to create a textarea rather than a text field. Updates
a couple textfield styles to facilitate this.

Preview link: https://docs-iqiblnualp.now.sh/

### CODE REVIEW

**Comment by dekkofilms** [comment]
Looks good ... I would approve, but it will just become stale. :)

**Comment by martahj** [comment]
@dekkofilms I haven't looked into that at all, no

**Comment by martahj** [comment]
@dekkofilms rebased 👍 I forgot to make a separate commit for it but this PR also fixes the scrolling issue we were seeing

**Comment by dekkofilms** [comment]
Awesome @martahj and I think @ashwoodall was asking about the resize thing. :)

**Pull request merged**
